# Generated by Django 4.2 on 2026-04-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='birth_year',
        ),
    ]
