# Generated by Django 4.2 on 2026-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0002_rename_age_user_birth_year'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ADD COLUMN IF NOT EXISTS "app_version" '
                            'varchar(32) NOT NULL DEFAULT \'\''
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ALTER COLUMN "app_version" DROP DEFAULT'
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ADD COLUMN IF NOT EXISTS "app_version_code" '
                            'integer NULL CHECK ("app_version_code" >= 0)'
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ADD COLUMN IF NOT EXISTS "client_platform" '
                            'varchar(32) NOT NULL DEFAULT \'\''
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ALTER COLUMN "client_platform" DROP DEFAULT'
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ADD COLUMN IF NOT EXISTS "level_generation_version" '
                            'varchar(64) NOT NULL DEFAULT \'\''
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'ALTER COLUMN "level_generation_version" DROP DEFAULT'
                        ),
                        (
                            'CREATE INDEX IF NOT EXISTS '
                            '"gameapi_fullreport_app_version_idx" '
                            'ON "gameapi_fullreport" ("app_version")'
                        ),
                        (
                            'CREATE INDEX IF NOT EXISTS '
                            '"gameapi_fullreport_app_version_code_idx" '
                            'ON "gameapi_fullreport" ("app_version_code")'
                        ),
                        (
                            'CREATE INDEX IF NOT EXISTS '
                            '"gameapi_fullreport_level_generation_version_idx" '
                            'ON "gameapi_fullreport" ("level_generation_version")'
                        ),
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "gameapi_fullreport_level_generation_version_idx"',
                        'DROP INDEX IF EXISTS "gameapi_fullreport_app_version_code_idx"',
                        'DROP INDEX IF EXISTS "gameapi_fullreport_app_version_idx"',
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'DROP COLUMN IF EXISTS "level_generation_version"'
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'DROP COLUMN IF EXISTS "client_platform"'
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'DROP COLUMN IF EXISTS "app_version_code"'
                        ),
                        (
                            'ALTER TABLE "gameapi_fullreport" '
                            'DROP COLUMN IF EXISTS "app_version"'
                        ),
                    ],
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='fullreport',
                    name='app_version',
                    field=models.CharField(blank=True, db_index=True, max_length=32),
                ),
                migrations.AddField(
                    model_name='fullreport',
                    name='app_version_code',
                    field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name='fullreport',
                    name='client_platform',
                    field=models.CharField(blank=True, max_length=32),
                ),
                migrations.AddField(
                    model_name='fullreport',
                    name='level_generation_version',
                    field=models.CharField(blank=True, db_index=True, max_length=64),
                ),
            ],
        ),
    ]
