# Generated by Django 4.2 on 2026-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameapi", "0003_fullreport_app_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        (
                            'CREATE TABLE IF NOT EXISTS "gameapi_fullreport_seed_levels" ('
                            '"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
                            '"fullreport_id" bigint NOT NULL REFERENCES "gameapi_fullreport" ("id") '
                            'DEFERRABLE INITIALLY DEFERRED, '
                            '"seedlevel_id" bigint NOT NULL REFERENCES "gameapi_seedlevel" ("id") '
                            'DEFERRABLE INITIALLY DEFERRED)'
                        ),
                        (
                            'CREATE UNIQUE INDEX IF NOT EXISTS '
                            '"gameapi_fullreport_seed_levels_fullreport_id_seedlevel_id_uniq" '
                            'ON "gameapi_fullreport_seed_levels" ("fullreport_id", "seedlevel_id")'
                        ),
                        (
                            'CREATE INDEX IF NOT EXISTS '
                            '"gameapi_fullreport_seed_levels_fullreport_id_idx" '
                            'ON "gameapi_fullreport_seed_levels" ("fullreport_id")'
                        ),
                        (
                            'CREATE INDEX IF NOT EXISTS '
                            '"gameapi_fullreport_seed_levels_seedlevel_id_idx" '
                            'ON "gameapi_fullreport_seed_levels" ("seedlevel_id")'
                        ),
                    ],
                    reverse_sql='DROP TABLE IF EXISTS "gameapi_fullreport_seed_levels"',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="fullreport",
                    name="seed_levels",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="full_reports",
                        to="gameapi.seedlevel",
                    ),
                ),
            ],
        ),
    ]
